### ISSUE TITLE
Simply does not work

### ISSUE THREAD

**Issue by DemonTraitor** [thebookisclosed/ShellFrosting#2]
Installed, applied. does not work.

**Comment by thebookisclosed** [comment]
Could you at least provide repro steps? How do you expect anyone to respond to this kind of issue?
What build are you using?

**Comment by DemonTraitor** [comment]
Sorry, just went through the palaver of removing what i already had in place - which i used to replace my actual original coded hack, and was a bit peeved to find it just did not work.

11 pro, 22h2, 22621.1702

installs, restarts explorer, select all the available options - nothing happens.

**Comment by thebookisclosed** [comment]
Just like issue #1, you've missed the clearly outlined supported builds explicitly mentioned
- [in the README](https://github.com/thebookisclosed/ShellFrosting#readme)
- [on the Releases page](https://github.com/thebookisclosed/ShellFrosting/releases)
- [in the Twitter post](https://twitter.com/thebookisclosed/status/1655686659436949507) (which publications often link to)

This is not a reimplementation of these features but a tool for enabling official code for them that is hidden in recent builds in an unfinished form.

**Comment by DemonTraitor** [comment]
I obviously did not read the docs proper. I'll go back to my original code.
I don't understand why the Devs at Microsoft can't just put this feature
back in. I cannot work proper without it

Powered by Tensor
