### ISSUE TITLE
Here are three problems I encountered

### ISSUE THREAD

**Issue by strongshuai** [thebookisclosed/ShellFrosting#3]
Here are three problems I encountered, I don’t know if they will be fixed? 
My English is not good, I use software to translate, I don’t know if it is accurate. 

1: The problem of icon loss can be switched between merging and not merging to recover, but it is very unstable. 

2: The title displayed on the taskbar is wrong and will not be updated to the title of the current window. 

3: The width of some taskbars will be longer and shorter for a while, and they will jump back and forth to make the visual experience very uncomfortable.

**Comment by thebookisclosed** [comment]
Thanks for letting me know, I'm aware of this category of issues and the stuff you've described most certainly falls under this bullet point:

> The root cause resides within Windows-provided code and is not a bug caused by the extension.

I might fix more broken OS level code in the future but I don't want to make any promises, it's pretty tedious.

**Comment by strongshuai** [comment]
Thank you for your reply. I guessed it too, because these problems are caused by the incomplete code that forcibly activates Microsoft’s unfinished feature. 
Let’s wait for Microsoft to improve this feature before using it. 
It’s not really worth spending time fixing these tedious problems right now. 
Use startallback first.
