### ISSUE TITLE
Need steps or script to make grouping work again on 22H2 22621

### ISSUE THREAD

**Issue by reddyshyam** [thebookisclosed/ShellFrosting#4]
Hi,

Totally my bad of running the app on latest public release of 22H2. I have uninstalled the app but for some reason grouping doesnot work as expected. Windows remain grouped but I cannot select a window of a group as I do not see popup when I click on the taskbar. Hope you can help me please.

![image](https://github.com/thebookisclosed/ShellFrosting/assets/12392746/ced74c16-3b80-4982-bef8-09f91aa29e94)

**Comment by gus33000** [comment]
Hi 👋

Are you able to open the registry editor (regedit), go under '''HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced''' and take a screenshots of all values shown on the right pane? It is possible some values like TaskbarGlomLevel and others are being read by 22621 for some functionality which would cause the loss of thumbnails and/or labels in thumbnails (personally experienced the latter).

**Comment by reddyshyam** [comment]
> Hi 👋
> 
> Are you able to open the registry editor (regedit), go under '''HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced''' and take a screenshots of all values shown on the right pane? It is possible some values like TaskbarGlomLevel and others are being read by 22621 for some functionality which would cause the loss of thumbnails and/or labels in thumbnails (personally experienced the latter).

Hi @gus33000,

Thanks for getting back. I appreciate the help. Here goes the screenshots.

![image](https://github.com/thebookisclosed/ShellFrosting/assets/12392746/a297778e-31cd-46eb-8910-ce7cb1e6a368)
![image](https://github.com/thebookisclosed/ShellFrosting/assets/12392746/3e45c7c4-0865-4f11-9d4d-edc53ad34665)

**Comment by gus33000** [comment]
Ok, it looks like you have TaskbarGlomLevel set to 2. Try setting it to 0 and see if your thumbnails come back

**Comment by reddyshyam** [comment]
> Ok, it looks like you have TaskbarGlomLevel set to 2. Try setting it to 0 and see if your thumbnails come back

Wow! Thanks @gus33000, you saved the day. 🙏Appreciate your time and help. 👍

Closing the ticket now.
